server :
  port : 9000
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
#    url: jdbc:mysql://8.131.110.2:3306/graduation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: graduation
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.graduation.enums
